### ISSUE TITLE
follow up with lever on payments

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/odd-ops#48]
From: "Pace, Ashley" <Ashley.Pace@austintexas.gov>
Date: Monday, June 11, 2018 at 7:24 AM
To: "Guhin, Ben" <Ben.Guhin@austintexas.gov>, "Wilhite, Marni" <Marni.Wilhite@austintexas.gov>
Subject: Fw: Lever Account Suspension

Please contact Lever about this.

Ashley Pace
Public Information Specialist
Austin Resource Recovery | City of Austin
Office 512-974-1855
austinrecycles.com

 
From: Lever Billing <billing@lever.co>
Sent: Saturday, June 9, 2018 2:05 AM
To: Pace, Ashley; Guhin, Ben; graham.pionkowski@lever.co; amy.ngai@lever.co
Subject: Lever Account Suspension 
 
Hello,

Good afternoon.  We contacted you over 2 weeks ago about an outstanding invoice.  Our records indicate that we still haven't received payment on invoice number  INV00021972.  The balance due on your account is $666.66 as of today.

Our billing department will suspend your account in three days if they don't receive payment.  Please let us know if we have made a mistake, or if there is anything we can do to help.

You may remit payment using the secure link below.

https://lever.secure.force.com/payments/PaymentMethodInput?id=2c92a0ff59b56b9c0159bd4346cc0c92 

Regards,
Lever Billing
billing@lever.co

**Comment by oliver2g** [comment]
Payment submitted just now. I also requested them to update the Lever account with my email address and remove Ashley's. I'll close this issue when a receipt is sent. @wilhitem and @benguhin please be on the lookout for a Lever receipt in case it ends up in your inbox.
