### ISSUE TITLE
Video documentation resources, software & hardware

### ISSUE THREAD

**Issue by toribr** [cityofaustin/odd-ops#51]
A copy of Camtasia, for screen and audio capture and editing capabilities (usability testing):
https://www.techsmith.com/store/camtasia
Special offer right now for $99 – let me know if you can’t get to that screen, it may be a result as a demo install.

Try this: https://www.techsmith.com/camtasia-mac-promo.html?utm_source=product&utm_medium=cmac&utm_campaign=cm3
 
A full-sized tripod (this one should do)
https://www.amazon.com/AmazonBasics-60-Inch-Lightweight-Tripod-Bag/dp/B005KP473Q/ref=sr_1_1_sspa?

**Comment by oliver2g** [comment]
@toribr let me know how to get to the $99 special offer. i can't see it.

**Comment by oliver2g** [comment]
@wilhitem let me know if you have any thoughts before purchasing the Camtasia software. We don't really have a criteria for evaluating purchases. In this case, the tool isn't very expensive.

**Comment by oliver2g** [comment]
Inquiring on how to purchase camtasia without paying sales tax since COA is tax exempt.

**Comment by oliver2g** [comment]
Purchased camtasia tax free @ $99/yr; tripod is still on the way

**Comment by oliver2g** [comment]
@toribr tripod delivered
