### ISSUE TITLE
Celine's laptop as design resource

### ISSUE THREAD

**Issue by toribr** [cityofaustin/odd-ops#52]
I'd like to get Celine's laptop back pronto, as it was the ONLY computer capable of printing to the printer without reinstalling the driver for every print. So we need it for that, and also I'm going to use it as a central usability testing machine.

**Comment by oliver2g** [comment]
@toribr let's talk about this today between sprit meetings. we should either be able to get your laptop to print or get a new printer.

**Comment by oliver2g** [comment]
@toribr does the user testing laptop have to be a mac?

**Comment by toribr** [comment]
Yes. But Ashley has one she can loan to the cause if getting one is an issue.

**Comment by oliver2g** [comment]
@toribr no worries. We have extra macbooks in our inventory. I'm working with CTM IT to get one ready this week.

**Comment by oliver2g** [comment]
@toribr I just heard back from CTM IT. We should have a macbook ready for testing tomorrow.

**Comment by oliver2g** [comment]
Laptop given to @toribr on 6/26
