### ISSUE TITLE
ODD July All Hands Agenda & Date

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/odd-ops#55]
Set date and venue for the next All Hands and create agenda

**Comment by wilhitem** [comment]
will send a calendar invite in the morning with location TBD. i'm thinking of scheduling over the liaison sync on 7/10 since we don't need to have that as a separate meeting that week.

Open to location. There are 14 people on the attendees list if all are present.

**Comment by oliver2g** [comment]
Scheduled for July 10, 2018. Location TBD

**Comment by wilhitem** [comment]
hey @oliver2g what do you think about doing this one back at city hall in that same room on the second floor? That worked well enough.

also, thinking for the next one we should move it to the afternoon and combine it with something fun.

**Comment by oliver2g** [comment]
@wilhitem sounds good to me. I like later in the day too. That way people can park in CH and just leave afterwards. Are you thinking 2-4pm?

**Comment by oliver2g** [comment]
@wilhitem FYI, no rooms available on either the first or second floor at CH. Still waiting to hear back from Josie about a room on the 3rd floor. If we're planning something fun, can we do it at a place like Irene's or elsewhere?

**Comment by oliver2g** [comment]
@wilhitem I reserved room 3102 (ten people) in CH from 11am-1pm tomorrow. Will this work? Do I need to change the time?
