### ISSUE TITLE
Purchase request: Get USB mice, keyboards and wrist supports 

### ISSUE THREAD

**Issue by toribr** [cityofaustin/odd-ops#56]
We need some USB mice for Faulk since a lot of the mac mice requiring charging, which is a problem, since it's often hard to find the cords with which to charge them. Also, usb keyboards would also be useful.

These will likely be fine: https://www.amazon.com/AmazonBasics-Wired-Keyboard-Mouse-Bundle/dp/B00B7GV802/ref=sr_1_3

Wrist pads and mouse pads are also needed. d
Here's a combo: https://www.amazon.com/Gimars-Nonslip-Support-Keyboard-Computer/dp/B01MYZMODY/ref=sr_1_11

**Comment by amenity** [comment]
Thanks, @toribr !

**Comment by oliver2g** [comment]
order placed today

**Comment by oliver2g** [comment]
Delivered
