### ISSUE TITLE
Update Dev position descriptions

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/odd-ops#7]

**Comment by oliver2g** [comment]
The Dev position descriptions in Lever are pretty old. We need to update them--Front-end, back-end, full stack

**Comment by mateoclarke** [comment]
@oliver2g I moved the existing descriptions from Lever to this Google Doc. Added the apprenticeship position and made a few edits. We can talk more as a team about which of these positions we should prioritize at our sync tomorrow.

https://docs.google.com/document/d/11bM7Wbm4Br-jvQHXXrZ6cLM08mvOgz8_N6FybZF7Huw/edit#

**Comment by oliver2g** [comment]
@mateoclarke and @benweatherman I think we're ok to close this issue. Let me know if you have any thoughts.
